package commons.enums;

public enum State {
    ACTIVE,
    BLOCKED,
    DESTROYED,
    COMPLETED,
    REJECTED,
    PENDING_CHALLENGE,
    EXPIRED,
    SUBMITTED,
    VERIFIED,
    INITIALISED,
    FAILED,
    PENDING,
    INACTIVE,
    PENDING_VERIFICATION,
    DEVICE_ALREADY_REGISTERED,
    DECLINED,
    ISSUED,
    RETURNED,
    INVALID,
    REQUIRES_SCA,
    PENDING_SCA,
    DECLINED_SCA,
    SCHEDULED,
    CANCELLED,
    PENDING_CONFIRMATION,
    PENDING_FUNDING,
    DEFERRED,
    PRE_MONITORING_SUSPENDED,
    EXECUTING,
    COMPLETED_WITH_ERRORS,
    PENDING_SETTLEMENT,
    REVALIDATE,

    // For testing purposes
    UNKNOWN
}
