package opc.enums.opc;

public enum InnovatorSetupDetails {
    PROGRAMME_ID,
    CORPORATE_PROFILE_ID,
    CONSUMER_PROFILE_ID,
    CORPORATE_MANAGED_ACCOUNT_PROFILE_ID,
    CONSUMER_MANAGED_ACCOUNT_PROFILE_ID,
    CORPORATE_CARD_PROFILE_ID,
    CONSUMER_CARD_PROFILE_ID,
    TRANSFERS_PROFILE_ID,
    SEND_PROFILE_ID,
    OWT_PROFILE_ID,
    SHARED_KEY,
    SECRET_KEY
}
